export const ALL_STORES = 'ALL_STORES'
export const SINGLE_STORE = 'SINGLE_STORE'
export const MODAL_SHOW = 'MODAL_SHOW'
export const MODAL_HIDE = 'MODAL_HIDE'
export const SKELETON_START = 'SKELETON_START'
export const SKELETON_END = 'SKELETON_END'
